Authorization - login and register
ExtensionEngine/chichet pull request #13
Opened 2022-07-13 12:25 UTC by Lnola

The point was to add login and register endpoints on the **backend**.
We had to add new env variables, two endpoints ('/users/login' and '/user/register') and updated models. After this PR we should have the project set up for frontend form creation and authentication on the backend (PR coming in the future)

Main functionality of register is to add the user to the database with hashed password and return the access token to the user

Main functionality of login is to authenticate the user: check if the input credentials sent exist in the database and represent a real user. If they do, it should return an access token

Testing - start the dev server with `docker compose up` and run the migration and seed. Use postman/insomnia to send requests.
Testing register - pass the following parameters to the request body - firstName:string, lastName:string, username:string (unique), password:string
Testing login - (add a few users with register first) - pass the following parameters to the request body - username:string (unique), password:string

We haven't yet setup a global error handling system so be gentle 😅 

Closes #11

2022-07-13 12:58 UTC, nk38104 submitted a review, later dismissed
Looks good to me 😄

2022-07-13 13:03 UTC, bdeak4 requested changes
Looks good except lil suggestion about error message

2022-07-13 13:03 UTC, bdeak4 commented on docker-compose.yaml
> +      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET?err}
Good choice using docker compose for handling .env 🚀

2022-07-13 13:11 UTC, bdeak4 commented on backend/src/shared/constants/errorMessages.ts
> +export const REGISTER_ERROR = 'Unable to create user, try different credentials.';
Yes, that is valid argument, but I think using package like this one https://www.npmjs.com/package/express-rate-limit would be better fit to handle this issue.

2022-07-13 13:13 UTC, Lnola commented on backend/src/shared/constants/errorMessages.ts
> +export const REGISTER_ERROR = 'Unable to create user, try different credentials.';
We thought about using something like that and decided against it (it's a bit overkill for a MVP/POC type of app)

2022-07-13 13:13 UTC, bdeak4 approved these changes

2022-07-13 13:16 UTC, bdeak4 approved these changes

2022-07-14 07:26 UTC, abasic reviewed
Looking good, love the attention to HTTP status codes. This is jus comment feedback, not a request for changes since I am leaving it up to you.

2022-07-14 07:26 UTC, abasic commented on .env.example
> +ACCESS_TOKEN_SECRET=
The scope of this comment is outside of this PR but since environment variables are introduced in this PR and used in `docker-compose.yaml` I'll write it here. Are there additional variables that can be moved to this file since it has been introduced?

2022-07-14 08:00 UTC, Lnola commented on .env.example
> +ACCESS_TOKEN_SECRET=
we were thinking of moving all database config data from the docker-compose.yaml and config.js files, but the fact is that the data about the database is just the 'docker data' used to run docker on your local machine and it will never be used in a real environment. If we deploy the app the data will of course be hidden, but since this is just a testing environment and isn't even user data (particular to any of our machines) it is fine if this stays

2022-07-14 08:02 UTC, Lnola commented on .env.example
> +ACCESS_TOKEN_SECRET=
you could say it's a lazy move so each of us doesn't personally have to think up a random name, password and so on for the database and it allows for easier testing and reviewing for someone that doesn't work directly on the code

2022-07-14 08:03 UTC, Lnola commented on backend/src/user/user.model.ts
> +    const saltRounds = +(process.env.SALT_ROUNDS as string);
I love using the `+` operator for casting, but I see where you are coming from. We'll use one of the more common ways 😄

2022-07-14 08:07 UTC, Lnola commented on backend/src/shared/database/migrations/20220708085618-create-user.js
> +      username: {
That was actually a huge oversight, thanks for pointing it out! Since we were dropping the docker images like crazy we didn't even notice that, but yes, I think this change should be in a new migration. What do you think @sandje00

2022-07-14 08:17 UTC, sandje00 commented on backend/src/shared/database/migrations/20220708085618-create-user.js
> +      username: {
@Lnola I agree with you.

2022-07-14 08:22 UTC, sandje00 commented on backend/src/user/index.ts
> +router.get('/', getAll).post('/login', login).post('/register', register);
@bdeak we were thinking about the time once we have an authorization middleware. This way, we can only add `.use(authMiddleware)` in the chain, and after that point all of the following methods in the chain are protected.

If we add each method to the router object separately, authorization middleware would need to be repeatedly included to every route.

2022-07-14 09:41 UTC, abasic commented on .env.example
> +ACCESS_TOKEN_SECRET=
Fair enough 😄 . Related to the lazy part, the `.env.example` could have the same ones as the ones that are hardcoded in the `docker-compose.yaml` and `config.js` files so that they could just be copied 🤓

2022-07-14 10:05 UTC, abasic approved these changes
@Lnola @sandje00 Looks good 👍 . Can be merged.

2022-07-14 10:15 UTC, merged