Authorization
ExtensionEngine/chichet pull request #19
Opened 2022-07-18 14:01 UTC by sandje00

Closes #15

2022-07-20 20:18 UTC, sandje00 reviewed
Please, could you read the comments before reviewing. 👇

2022-07-20 20:18 UTC, sandje00 commented on backend/src/shared/auth/refresh.ts
> +    if (!user || id !== user.id || username !== user.username || aud !== Audience.Scope.Refresh) {
I am aware this is just a hack rather than a clean solution; I would like to replace it with the better solution of the problem, but since finding it took far too much of my time, I decided to avoid the problem temporarily this way to finish the functionality and get the rest of the code ready for the review.

THE PROBLEM:
Even though Express Request interface is extended (`@types/express/index.d.ts`) with `user` property of type `User` (which is a user model), inside `refresh` middleware function TS recognises fetched user as a Sequelize model, but not as user model instance specifically, which means that TS forbids accessing instance data properties and instance methods.

Inside `@types/express/index.d.ts` I have tried to set type of `user` property:

- custom `IUser` interface that exists on branch main
- user model that implements `IUser` interface that exists on branch main
- user model newly rewritten in accordance with (Sequelize documentation)[https://sequelize.org/docs/v6/other-topics/typescript/]
- writing all the data properties and instance methods manually.

The only of those four that worked was the last one, but it would be much better to leverage what has already been defined, i. e. something like the first three.

I am open to any ideas that would help to solve the problem.

2022-07-20 20:18 UTC, sandje00 commented on backend/src/shared/auth/refresh.ts
> +    const { accessToken: newAccessToken, refreshToken: newRefreshToken } = await user.generateTokens();
The same as the previous comment.

2022-07-20 20:18 UTC, sandje00 commented on backend/src/user/user.model.ts
> +  declare refreshToken: CreationOptional<string>;
I have rewritten the user model this way because I thought it would help solving the problem described in the first comment. Although it has not helped, this approach to TS Sequelize model definition seems more concise than declaring user interface manually and then implementing it on user model. For that reason, I kept this code and I think we should consider adopting this approach in other model definitions.

2022-07-21 09:41 UTC, Lnola requested changes
The logic is good, we just need to tweak a few implementation details for an approve

2022-07-21 09:41 UTC, Lnola commented on backend/src/user/user.model.ts
> +  private _generateRefreshToken(): string {
`_generateAccessToken` and `_generateAccessToken` are the same function with different parameters

you could add a tokenType like this

```
type ITokenType = 'ACCESS' | 'REFRESH';
```
and then do this

```
private _generateToken(tokenType: ITokenType) {
    const secret = process.env[`${tokenType}_TOKEN_SECRET`] || '';
    const options = {
      audience: Audience.Scope.Refresh,
      expiresIn: process.env[`${tokenType}_TOKEN_DURATION`],
    };

    const { id, username } = this;
    const payload = { id, username };
    return jwt.sign(payload, secret, options);
  }
```

or store the env data inside an object and index it with the key

```
const tokenData = {
      access: {
        secret: process.env.ACCESS_TOKEN_SECRET,
        duration: process.env.ACCESS_TOKEN_DURATION,
      },
      refresh: {
        secret: process.env.REFRESH_TOKEN_SECRET,
        duration: process.env.REFRESH_TOKEN_DURATION,
      },
    };

const secret = tokenData[tokenType].secret || '';
    const options = {
      audience: Audience.Scope.Refresh,
      expiresIn: tokenData[tokenType].duration,
    };
```

2022-07-21 09:43 UTC, Lnola reviewed
Oh and please resolve the conflicts with main

2022-07-21 09:48 UTC, sandje00 commented on backend/package.json
> +    "dev": "nodemon -r tsconfig-paths/register --files src/app.ts",
Yes, it is for custom interface extensions in `./src/@types` to be loaded and applied.

2022-07-21 11:03 UTC, sandje00 commented on backend/src/shared/auth/authenticate.ts
> +  try {
I will definitely add a blank line to improve readability (sorry, the mentality from some previous projects). The reason I am not using one line if in `authenticate` and `refresh` particularly is so that the lines don't get too long.

2022-07-21 14:26 UTC, sandje00 commented on backend/src/@types/express/index.d.ts
> +}
I believe this is still going to be necessary in order to be able to attach user to `req` object.

2022-07-21 14:31 UTC, sandje00 commented on backend/src/shared/auth/refresh.ts
> +    if (!user || id !== user.id || username !== user.username || aud !== Audience.Scope.Refresh) {
Regarding the first comment you made: haven't we exported all of the models in `shared/database/index` in order to be able to use them across the application and use files like `user.model.ts` only inside `user` folder (which applies for other entities, as well)?

2022-07-21 14:51 UTC, Lnola commented on backend/src/shared/auth/refresh.ts
> +    if (!user || id !== user.id || username !== user.username || aud !== Audience.Scope.Refresh) {
yes, but if you look inside `user.controller.ts` we used the model directly and we said that it should be changed in the future. I'd say that for now it is ok to have it that way and to change it later.

For the last hour I've been trying to solve this issue and I've found a way to do it. Since we don't have a production I'm fine with this going into `main` but it doesn't have to since I'll be changing it in a few minutes 😄

2022-07-21 14:51 UTC, Lnola commented on backend/src/shared/auth/refresh.ts
> +    if (!user || id !== user.id || username !== user.username || aud !== Audience.Scope.Refresh) {
I think we should follow what we've done in user.controller and push it like that (so from the model, not from the index.ts), even though it's not ideal, it is the way we did it and we should be consistent. 

That way we have a consistent base to come to and changes to it are done in a different PR since many side changes in one PR are generally not a good idea - separate issues in their separate pull requests

2022-07-21 14:57 UTC, Lnola commented on backend/src/shared/auth/authenticate.ts
> +  try {
just an FYI, it's fine if it stays like that (one liners I mean), but to note that we've set the `printwidth` in `prettierrc` so you don't have to worry about lines being to long - prettier will automatically put them in new line if they are too long

2022-07-21 15:05 UTC, Lnola commented on backend/src/@types/express/index.d.ts
> +}
I'd say this is a bit overkill when you can just do 

```
interface IUserRequest extends Request {
  user: typeof User;
}
```

or

```
type IUserRequest = Request & {
  user: typeof User;
};
```

2022-07-21 15:09 UTC, Lnola commented on backend/src/shared/auth/refresh.ts
> +      return res.status(403).json({ error: errorMessages.FORBIDDEN_ERROR });
think you missed one 😄 
`error` -> `message`

2022-07-21 15:15 UTC, Lnola commented on backend/src/config/authTokens.ts
> +import Audience from 'shared/auth/audience';
can you explain why this is in the config folder in src. I would probably put it in `shared/constants` or in `shared/auth`

2022-07-21 15:17 UTC, Lnola commented on backend/src/shared/auth/helpers.ts
> +import { IGeneratedTokens } from 'user/types';
nitpick - I'd put this in `shared/helpers/auth` or `shared/utils/auth`

2022-07-21 15:24 UTC, abasic commented on backend/src/shared/auth/authenticate.ts
> +    const { id, aud } = jwtVerify(accessToken, process.env.ACCESS_TOKEN_SECRET || '') as IJwtPayloadDecoded;
There was no value in this [types](https://www.npmjs.com/package/@types/jsonwebtoken) package?

2022-07-21 15:24 UTC, abasic commented on backend/src/shared/auth/authenticate.ts
> +    if (!user || aud !== Audience.Scope.Access) {
Nitpick: the audience can be checked before fetching the user so there is no need to do the database query.

2022-07-21 15:24 UTC, abasic commented on backend/src/shared/auth/authenticate.ts
> +    return res.status(403).json({ message: errorMessages.FORBIDDEN_ERROR });
Nitpick: There are [npm packages](https://npms.io/search?q=http+status) that can be used instead of the number for the status code. They are more informative.

2022-07-21 15:24 UTC, Lnola requested changes
I think `@types/express/index.d.ts` and using the `user.model.ts` need to be changed or at least commented about more before we can merge with main

2022-07-22 07:38 UTC, sandje00 commented on backend/src/shared/auth/authenticate.ts
> +    return res.status(403).json({ message: errorMessages.FORBIDDEN_ERROR });
I guess this should be implemented as a part of global error handling PR.

2022-07-22 07:56 UTC, sandje00 commented on backend/src/config/authTokens.ts
> +import Audience from 'shared/auth/audience';
Because you can reason about this file as configuration for further token usage.

2022-07-22 08:20 UTC, Lnola commented on backend/src/@types/express/index.d.ts
> +      user: User;
the fix is - put it as `typeof User`

however, there is a problem with that. If you do that you get this error in `authenticate.ts` on `req.user`

`Type 'User' is not assignable to type 'ModelStatic<Model<any, any>>'.`

That is the same error cause by importing user from `database/index.ts` as the other ones

2022-07-22 08:27 UTC, Lnola commented on backend/src/config/authTokens.ts
> +import Audience from 'shared/auth/audience';
makes sense

2022-07-22 08:39 UTC, Lnola commented on backend/src/@types/express/index.d.ts
> +      user: User;
and leaving a comment here since I'm not getting a response to the other one

I'm against using a declaration file for solving something we created. Declaration files describe the shape of external libraries and help typescript understand what they should look like. Since `User` is not a normal part of Express, but something we add to the existing express `Request` inside our own code it should be an interface or type that only extends the `Request` with the `user` attribute (that is type `typeof User`)

sorry for being a pain 😕

2022-07-22 14:33 UTC, abasic approved these changes

2022-07-25 06:38 UTC, Lnola approved these changes

2022-07-25 06:43 UTC, merged