Tag selection
ExtensionEngine/chichet pull request #22
Opened 2022-07-19 08:46 UTC by Lnola

Closes #21

2022-07-19 18:41 UTC, sandje00 commented on frontend/src/api/tag.js
> +function fetch() {
Can we use more descriptive name, e. g. `fetchAll`?

2022-07-19 18:41 UTC, sandje00 commented on frontend/src/components/tags/TagList.vue
> +  direction: ltr;
Just a question; isn't `ltr` a default value for property `direction`?

2022-07-19 18:41 UTC, sandje00 commented on frontend/src/components/tags/TagSelect.vue
> +    const areAnySelected = () => {
Do you think it makes sense to make `areAnySelected` a computed property?

2022-07-20 06:41 UTC, Lnola commented on frontend/src/api/tag.js
> +function fetch() {
renamed to `fetchAll`

2022-07-20 06:48 UTC, Lnola commented on frontend/src/components/tags/TagList.vue
> +  direction: ltr;
Yes, it is. The reason I did this is a CSS "hack" to set the scrollbar left instead of right. I switched the parents default direction to `rtl` to swap the position of the scrollbar to left but then I had to revert the content direction back to the left with this line. Since the parent is the one with the `overflow: scroll` attribute it has the scrollbar and by setting it's direction to the left I set the scrollbar left, but then had to revert the content back so only the scrollbar moves

2022-07-20 07:33 UTC, sandje00 commented on frontend/src/components/tags/TagSelect.vue
> +    <chi-button v-if="areAnySelected()" @click="handleSaveSelected" class="select-skip" inline>Continue >></chi-button>
It is possible to use a computed property like a variable, so `()` is not necessary.

2022-07-20 07:33 UTC, abasic requested changes

2022-07-20 07:33 UTC, abasic commented on frontend/src/api/config.js
> +  baseURL: import.meta.env.VITE_API_PATH,
Can baseURL here be relative or does it need to be absolute (like it is defined in `docker-compose.yaml`?

2022-07-20 07:33 UTC, abasic commented on frontend/src/api/config.js
> +  baseURL: import.meta.env.VITE_API_PATH,
And can something be done the `vite` way?

2022-07-20 07:33 UTC, abasic commented on frontend/src/components/tags/TagList.vue
> +  direction: ltr;
👌 (Can not react with this one so I am writing a comment).

2022-07-20 07:33 UTC, abasic commented on frontend/src/components/tags/TagSelect.vue
> +      tagsArray.forEach(tag => {
Can `map` be used instead? Or is there an issue with the `reactive` concept?

2022-07-20 07:33 UTC, abasic commented on frontend/src/components/tags/TagSelect.vue
> +    <chi-button v-if="areAnySelected()" @click="handleSaveSelected" class="select-skip" inline>Continue >></chi-button>
I believe there is no need for the brackets when using a `computed`.

2022-07-20 07:33 UTC, abasic commented on frontend/src/components/tags/TagSelect.vue
> +  margin-left: -20px;
I haven't run this yet (my bad) but I am wary of negative margines. I assume this is because of the scroll on the left side. Could you please expand as to what this is trying to achieve?

2022-07-20 07:33 UTC, abasic commented on frontend/src/components/tags/TagSelect.vue
> +    <chi-button v-else @click="handleProceed" class="select-skip" inline>Skip for now >></chi-button>
From the users perspective, what is gained by not allowing them to skip even though they have selected something?

2022-07-20 08:18 UTC, Lnola commented on frontend/src/components/tags/TagSelect.vue
> +    <chi-button v-else @click="handleProceed" class="select-skip" inline>Skip for now >></chi-button>
Valid point. It was a way of decluttering using just 1 button instead of 2 but UX is more important than UI, I'll update this!

2022-07-20 08:33 UTC, Lnola commented on frontend/src/components/tags/TagSelect.vue
> +      tagsArray.forEach(tag => {
I was having issues with making the array reactive - couldn't save the fetched data directly into it, couldn't use `concat`, only push seemed to work. After I got this working I ended up changing a few things so I'll look into if this is possible to do now.

2022-07-20 08:53 UTC, abasic commented on frontend/src/api/config.js
> +  baseURL: import.meta.env.VITE_API_PATH,
The answers to these two questions are different so reading them again I see they are confusing. Sorry about that.

The URL is absolute in the `docker-compose.yaml` (http://localhost:3001). The browser by default sends the payload to the domain of the webpage that is hosting the site. In this case, it would be http://localhost:3000.

Starting from the second question, `vite` has a [proxy](https://vitejs.dev/config/server-options.html#server-proxy) option which I believe should be leveraged for this. In development, the frontend is hosted by a vite server that is different from the backend server (and thus a different URL) but (usually) in production they should be behind the same URL. So having the `axios` configuration reference the URL of the backend directly does not seem like a clean solution. The development can mimic a typical production environment (frontend and backend behind the same URL) and avoid coupling the frontend code with the configuration.

After answering the second question the first becomes obsolete in my eyes. At least from the perspective of this project. But the answer would be that it can be relative, and it probably should. It will come into play if you put some of your prefix your routes with `/api/`. Which is a pattern some follow. Hope this clears it up. Sorry again for the confusing questions.

2022-07-20 08:56 UTC, abasic commented on frontend/src/components/tags/TagSelect.vue
> +  margin-left: -20px;
Fair enough 😄 . Just a note since you are playing around with it: the scroll behavior on Mac OS can be changed to work like Windows (always visible). You can change it [here](https://www.lifewire.com/change-how-macs-scroll-bars-work-2260834). If you have not seen it, it might be useful for playing around with this and seeing how it behaves.

2022-07-20 09:16 UTC, Lnola commented on frontend/src/api/config.js
> +  baseURL: import.meta.env.VITE_API_PATH,
This makes so much sense! I'm glad you explained it since I haven't had much experience with something like this. I'll play around with it a bit now. Never thought about this before, will do for this project and in the future! 🚀

2022-07-22 06:16 UTC, abasic requested changes

2022-07-22 06:16 UTC, abasic commented on backend/src/app.ts
> +app.use(createEndpoint(user.path), user.router);
Nitpick: Another way to do this is to create a new parent router and use it instead of `app` so that all these subroutes are set up on it. And then set that parent router to be on `/api`. In code terms something like this:

```js
import { Router } from 'express';

const router = Router();

router.use(message.path, message.router);
router.use(room.path, room.router);
router.use(tag.path, tag.router);
router.use(user.path, user.router);

app.use('/api', router);
```
I believe this is a cleaner approach that leverages how `express` handles routes.

2022-07-22 06:16 UTC, abasic commented on frontend/src/api/tag.js
> +  root: '/api/tags',
Every new URL set up this way will start with `/api`. Is there a way to make it so their URLs need to only reference the part of the URL that is unique to them? Hint: this is connected to the `axios` `baseURL` question from earlier 😄

2022-07-22 06:16 UTC, abasic commented on frontend/src/components/tags/TagList.vue
> +import ChiButton from '../common/ChiButton.vue';
Hint: such common components can be [registered globally](https://vuejs.org/guide/components/registration.html#global-registration) so they do not need to be imported into each component that uses them 🤓

2022-07-22 06:16 UTC, abasic commented on frontend/src/components/tags/TagSelect.vue
> +      tags.push(...(await tagApi.fetchAll()));
I'll look into if this can be done that does not rely on push.

2022-07-22 06:16 UTC, abasic commented on frontend/src/components/tags/TagSelect.vue
> +      tags.map(tag => (tag.selected = false));
The intention for `Array.map` is to be used to create a new array that is based on an existing one. Since here it is only used to loop through the existing array, `forEach` is more appropriate.

2022-07-22 06:28 UTC, abasic commented on frontend/src/components/tags/TagSelect.vue
> +      tags.push(...(await tagApi.fetchAll()));
I played around with it and it seems this can not be done when making an array reactive with the `reactive` method. The `ref` method needs to be used. Their [documentation](https://vuejs.org/guide/essentials/list.html#array-change-detection) also mentions it.

2022-07-22 06:40 UTC, Lnola commented on backend/src/app.ts
> +app.use(createEndpoint(user.path), user.router);
much cleaner, love it 😍

2022-07-22 07:35 UTC, Lnola commented on frontend/src/components/tags/TagSelect.vue
> +      tags.push(...(await tagApi.fetchAll()));
I can do something like this when using `ref`

```
const tagsArray = await tagApi.fetchAll();
tags.value = tagsArray.map(tag => ({ ...tag, selected: false }));
```

it can even be a one-liner but I think something like this looks cleaner

2022-07-22 14:37 UTC, abasic submitted a review, later dismissed

2022-07-25 06:53 UTC, sandje00 approved these changes
🚀

2022-07-25 06:53 UTC, merged