Persist user on login (protected routes)
ExtensionEngine/chichet pull request #31
Opened 2022-07-26 10:00 UTC by Lnola

2022-07-26 14:58 UTC, abasic requested changes

2022-07-26 14:58 UTC, abasic commented on frontend/src/components/auth/UserRegister.vue
> +    console.log(userStore.getUser);
👀

2022-07-26 14:58 UTC, abasic commented on frontend/src/components/auth/UserSignIn.vue
> +import { useAuthStore } from '../../store/authStore';
Sometimes `@` is used, and sometimes it is not. Please be consistent.

2022-07-26 14:58 UTC, abasic commented on frontend/src/router/index.js
> +router.beforeEach(async (to, from) => {
I believe `async` is not needed here.

2022-07-26 14:58 UTC, abasic commented on frontend/src/router/index.js
> +  }
I believe this code can be rewritten so it is more easily understood and extended down the line. For example:
```js
const isLoggedIn = !!user.id;
const isAuthRoute = to.name === 'Auth';

if (!isLoggedIn && !isAuthRoute) return { name:  'Auth'  };
if (isLoggedIn && isAuthRoute) return { name: 'Home'  };
```
or
```js
const isLoggedIn = !!user.id;
const isAuthRoute = to.name === 'Auth';

if (isLoggedIn) {
  if (isAuthRoute) return { name: 'Home' };
} else {
  if (!isAuthRoute) return { name: 'Auth' };
}
```
The general idea is to extract some parts of the logic into variables so it is easier to keep track of what is happening and what is being used to decide where to redirect.

2022-07-27 06:46 UTC, Lnola commented on frontend/src/components/auth/UserRegister.vue
> +    console.log(userStore.getUser);
hahahhaha, you saw NOTHING!!!

2022-07-27 06:50 UTC, Lnola commented on frontend/src/components/auth/UserSignIn.vue
> +import { useAuthStore } from '../../store/authStore';
I try to be consistent with using @, this was an auto import that managed to slip through! I'll be more attentive to it next time!

2022-07-27 06:57 UTC, Lnola commented on frontend/src/router/index.js
> +router.beforeEach(async (to, from) => {
Yep, forgot to remove it when I removed the authenticate call (old logic)

2022-07-27 07:01 UTC, Lnola commented on frontend/src/router/index.js
> +  }
I agree (I went with the first option)

2022-07-27 08:31 UTC, sandje00 submitted a review, later dismissed
Everything looks good! 😃

2022-07-27 08:31 UTC, sandje00 commented on frontend/src/store/authStore.js
> +  const user = ref(useStorage('user', {}));
Nice! 🚀

2022-07-27 08:50 UTC, abasic submitted a review, later dismissed
One small note for future sake. :D

2022-07-27 08:50 UTC, abasic commented on frontend/src/router/index.js
> +  const isLoggedIn = !!useAuthStore().getUser.id;
This could have been a [getter](https://pinia.vuejs.org/core-concepts/getters.html) in pinia. Now it is only used here but it might come into play later on.

2022-07-27 08:52 UTC, Lnola commented on frontend/src/router/index.js
> +  const isLoggedIn = !!useAuthStore().getUser.id;
I like that idea, `id` should be used a lot later

2022-07-27 09:07 UTC, abasic approved these changes

2022-07-27 09:09 UTC, merged