Add and use user tags
ExtensionEngine/chichet pull request #39
Opened 2022-07-27 12:47 UTC by Lnola

Update to `//TODO: ` from #21

The point was to implement connecting the user to tags. That included adding bulk add of `UserTags` endpoint and implementation on `continue` click. Beside that the `tags.model.ts` was updated with type definition and tags `getAll` method was updated to arrive on the frontend mapped with the `selected` attribute. 

Testing is simple - go to `/tags` after registration, and click on some tags. When finished click on continue. Upon return you should see the previously selected tags still selected and be able to update them again

Closes #38

2022-07-28 09:06 UTC, abasic requested changes

2022-07-28 09:06 UTC, abasic commented on backend/src/shared/database/migrations/20220727125920-add-unique-to-user-tag.js
> +      name: 'unique_ids',
Nitpick: a more descriptive name should be used for this liike `unique_user_id_tag_id`. I believe constraint names are unique across all tables so the proposed name might not be unique enough.

2022-07-29 06:37 UTC, Lnola commented on backend/src/tag/tag.controller.ts
> +  const userId = req.user?.id;
We cannot leave the `?` out because `typeof user = User | undefined`

2022-07-29 06:40 UTC, Lnola commented on backend/src/tag/tag.controller.ts
> +    const tagsToDisplay = tags.map(({ id, label, users }) => ({ id, label, selected: users.length !== 0 }));
I tried that and had something close to a solution but I didn't like it over what was done here. I'll try again!

2022-07-29 06:47 UTC, Lnola commented on backend/src/userTag/userTag.model.ts
> +      uniqueKeys: {
I found this in a stackoverflow answer and it worked so I thought that was the answer. Now that I've read the documentation I'm doing it that way!

2022-07-29 07:10 UTC, Lnola commented on backend/src/tag/tag.controller.ts
> +        through: { attributes: [] },
It wasn't needed since I had to rewrite the `findAll` but I'll keep this in mind in the future

2022-07-29 08:31 UTC, abasic requested changes

2022-07-29 08:31 UTC, abasic commented on backend/src/userTag/userTag.controller.ts
> +    );
This is a good place to use a transaction since, if the `bulkCreate` fails for some reason, the `destroy` does not go through.

2022-07-29 08:31 UTC, abasic commented on frontend/src/components/tags/TagSelect.vue
> +import { useAuthStore } from '../../store/authStore';
Nitpick: a path starting with `@` can be used instead of the relative path.

2022-07-29 08:31 UTC, abasic commented on backend/src/userTag/userTag.model.ts
> +      uniqueKeys: {
If you are referring to [this](https://stackoverflow.com/questions/42195348/how-to-define-unique-index-on-multiple-columns-in-sequelize/48563370#48563370) post, I believe it might only apply to the `createTable` method of the query interface. But this being Sequelize, it would not surprise me if it worked but just not documented correctly.

2022-07-29 08:43 UTC, Lnola commented on frontend/src/components/tags/TagSelect.vue
> +import { useAuthStore } from '../../store/authStore';
I'll look into some kind of editor config/lint to see this as an error, I keep missing these

2022-07-29 08:45 UTC, Lnola commented on backend/src/userTag/userTag.model.ts
> +      uniqueKeys: {
Not just that post, I found it in multiple places as the first answer for models 😄 
Sequelize documentation MVP!

2022-07-29 09:07 UTC, abasic requested changes

2022-07-29 09:07 UTC, abasic commented on backend/src/userTag/userTag.controller.ts
> +  const transaction = await sequelize.transaction();
The transaction needs to be passed as a prop to both `destroy` and `bulkCreate` for them to be a part of it. See the [documentation](https://sequelize.org/docs/v6/other-topics/transactions/#unmanaged-transactions) for more info.

2022-07-29 09:08 UTC, Lnola commented on backend/src/userTag/userTag.controller.ts
> +  const transaction = await sequelize.transaction();
I truly am blind....

2022-07-29 11:43 UTC, sandje00 approved these changes
👌

2022-07-29 13:20 UTC, merged