User Profile
ExtensionEngine/chichet pull request #40
Opened 2022-07-27 20:57 UTC by sandje00

Closes #34

2022-07-29 10:25 UTC, Lnola commented on backend/src/user/user.model.ts
> +        get(this: IUser): string {
I don't believe the return type for this function is needed

2022-07-29 10:57 UTC, abasic requested changes
Mostly nitpicks 👍

2022-07-29 10:57 UTC, abasic commented on frontend/src/assets/stylesheets/common/all.css
> +@import 'global.css';
This is already imported above.

2022-07-29 10:57 UTC, abasic commented on frontend/src/composables/useToggle.js
> +  const isTrue = ref(false);
Nitpick: `isToggled` or `isSet` might be better names because `isTrue` does not seem as specific as it needs to be.

2022-07-29 10:57 UTC, abasic commented on frontend/src/components/userProfile/index.vue
> +        <user-form :inputs="formInputs" class="user-profile-form" disabled />
Nitpick: the design does not really reflect that the form is disabled. So, if this is not temporary (set up for another PR), I would advise revisiting this design and making a disabled `user-form` visually different from no active one.

2022-07-29 10:57 UTC, abasic commented on frontend/src/components/userProfile/index.vue
> +import UserForm from '../auth/UserForm.vue';
Nitpick: relative paths are used. In #44 that will no longer be allowed. So please update these paths.

2022-07-29 10:57 UTC, abasic commented on frontend/src/components/tags/TagList.vue
> +        :class="{ small }"
Nitpick: maybe make this an attribute of the `chi-button` component. So that it can dictate how its small style will look like. And that it can be set to be small in other components as well.

2022-07-29 10:57 UTC, abasic commented on backend/src/user/user.controller.ts
> +  return res.status(OK).json({ id, username, firstName, lastName, fullName });
Hint: by making another virtual field or a getter on the user class and moving all of this information to it, it would simplify any code that requires only this specific subset of the user information. For example:
```js
// user.model.ts
...
profile: {
  type: VIRTUAL,
  get(this: IUser): string {
    return {
      id: this.id,
      username: this.username,
      firstName: this.firstName,
      lastName: this.lastName,
      fullName: this.fullName
    };
  },
},
...

// or

get profile() {
  return {
    id: this.id,
    username: this.username,
    firstName: this.firstName,
    lastName: this.lastName,
    fullName: this.fullName
  };
}

// user.controller.ts
return res.status(OK).json(user.profile);
```
By doing something like this, only that getter or virtual field needs to be updated if new info needs to be added or removed.

2022-07-29 11:09 UTC, Lnola requested changes

2022-07-29 11:09 UTC, Lnola commented on frontend/src/components/userProfile/index.vue
> +<style scoped>
love the transition of the user profile flying in, would love to see it fly away (doesn't need to be added now, we can focus on animations later if we want to do them)

2022-07-29 11:09 UTC, Lnola commented on frontend/src/components/userProfile/index.vue
> +  height: 100vh;
these two probably could be `%`. I'd avoid using viewport units and especially `vw` (because of the scrollbar issue). The parent can have them, fine, (though I think the parent should have `%` also) but this should be `%` if it can be

2022-07-29 11:09 UTC, Lnola commented on frontend/src/components/userProfile/index.vue
> +  position: fixed;
this doesn't need to be `fixed` if the parent already is

2022-07-29 11:09 UTC, Lnola commented on frontend/src/components/userProfile/index.vue
> +  border-radius: 0 0 120px 0;
`border-bottom-left-radius: 120px`

2022-07-29 11:09 UTC, Lnola commented on frontend/src/components/userProfile/index.vue
> +  position: fixed;
the position also doesn't need to be set. If you remove these 3 lines (position, top, left) everything still works the same

2022-07-29 11:09 UTC, Lnola commented on frontend/src/components/userProfile/index.vue
> +  transition-property: left;
shorthand would be: `transition: margin-left 0.6 ease`

2022-07-29 11:12 UTC, Lnola commented on frontend/src/components/userProfile/index.vue
> +        <user-form :inputs="formInputs" class="user-profile-form" disabled />
@sandje00 you can use the `--color-primary-subdued` for input coloir and change the text color too to make it look disabled

2022-07-29 11:21 UTC, sandje00 commented on frontend/src/assets/stylesheets/common/measures.css
> +  --z-user-profile-container: 30;
In my view it is useful to have z indices as variables in one place because in case of adding new element that also has z index it is easier to determine such value of its z index that has no collision with existing elements.

2022-07-29 11:29 UTC, sandje00 commented on frontend/src/components/tags/TagList.vue
> +    <div :class="{ centred }" class="tag-list">
I appreciate your sense for details; I agree that we should stick to the convention. I will fix it, but after my tea time. 🍵

2022-07-29 13:35 UTC, abasic commented
@sandje00 please resolve the conflicts as well.

2022-08-01 09:20 UTC, sandje00 commented on frontend/src/components/userProfile/index.vue
> +<style scoped>
Maybe we could add entire animation as a part of separate PR.

2022-08-01 11:32 UTC, Lnola requested changes
Minor changes needed and it will be good to go!

2022-08-01 11:32 UTC, Lnola commented on frontend/src/components/profile/ProfileSidebar.vue
> +        <user-form :inputs="formInputs" class="user-profile-form" disabled />
Can we add some kind of `v-if` to not show the empty `Full name` (since it is optional in user profile creation)

2022-08-01 11:32 UTC, Lnola commented on frontend/src/components/profile/ProfileSidebar.vue
> +    // Replace with composables
can you replace this with `// TODO: Replace with composables`
If you use this [extension](https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight) the text lights up orange to catch it easier 🍊

2022-08-01 11:32 UTC, Lnola commented on frontend/src/components/profile/ProfileSidebar.vue
> +  height: 100vh;
try this instead of setting width and height

```
top: 0;
right: 0;
bottom: 0;
left: 0;
```
or even better, the shorthand
```
inset: 0;
```

just an FYI, `inset` is not supported on every browser so check [this](https://caniuse.com/?search=inset) out before deciding to use it

2022-08-01 11:32 UTC, Lnola commented on frontend/src/components/profile/ProfileSidebar.vue
> +  height: 100vh;
this can be `%` instead of `vw` and `vh`. Since it is preferred in this scenario I'd change it to be `%`

2022-08-01 11:32 UTC, Lnola commented on frontend/src/components/profile/ProfileSidebar.vue
> +.active .user-profile-container {
nitpick: can this be closer to the original class that has `left: -100%` just fore readability

2022-08-01 11:32 UTC, Lnola commented on frontend/src/components/profile/ProfileSidebar.vue
> +.active .user-profile-overlay {
check this out `.active > .user-profile-overlay`

2022-08-01 11:32 UTC, Lnola commented on frontend/src/components/profile/ProfileSidebar.vue
> +.active .user-profile-container {
same as the previous comment - `.active > .user-profile-container`

2022-08-01 11:32 UTC, Lnola commented on frontend/src/components/profile/constants.js
> +    username: { label: 'Username', type: 'text', value: '', error: '', required: true },
just a question, would it work without the `type`, `error` and other unused attributes. If it cannot, then could we make it work by changing the original component?

2022-08-01 11:32 UTC, Lnola commented on frontend/src/components/tags/TagList.vue
> +        :large="!small"
could we make it `large` by default so we don't have to do this?

2022-08-01 12:04 UTC, abasic reviewed
Just minor comments that can be ignored.

2022-08-01 12:04 UTC, abasic commented on frontend/src/components/common/ChiButton.vue
> +}
Nitpick: personally I avoid setting margins in common components or in components that I know are intended to be used in different contexts. The reasoning is that the margin property defines how the component interacts with its surroundings (other components around it). So `margin` being defined in them can mess up the flow when being used in a new context. Usually what happens is that then these get overridden by styling outside of the component.

If you choose to do something about this at this point, my recommendation is to have specific classes that apply just the margins. And these classes would not be tied to buttons but could be used on anything.

2022-08-01 12:04 UTC, abasic commented on frontend/src/components/profile/ProfileSidebar.vue
> +  height: 100vh;
Could you elaborate why it is prefered in this scenario?

2022-08-01 12:04 UTC, abasic commented on frontend/src/components/tags/TagList.vue
> +        :large="!small"
Or maybe introduce a `size` attribute that consolidates the two.

2022-08-01 12:35 UTC, sandje00 commented on frontend/src/components/tags/TagList.vue
> +        :large="!small"
In that case it would impact "Register" and "SIgn in" buttons and I guess we don't want that.

2022-08-01 13:44 UTC, sandje00 commented on frontend/src/components/common/ChiButton.vue
> +}
This is going to be handled in a separate PR. 👍

2022-08-01 14:16 UTC, sandje00 commented on frontend/src/components/tags/TagList.vue
> +        :large="!small"
This comment has been resolved with #50 .

2022-08-01 14:31 UTC, sandje00 commented on frontend/src/components/profile/ProfileSidebar.vue
> +        <user-form :inputs="formInputs" class="user-profile-form" disabled />
Current implementation is rendering form fields with `v-for`. It is [not recommendable to use `v-if` with `v-for`](https://learnvue.co/tutorials/vue-for-loop-tips#avoid-use-v-if-in-loops) and the linter does not allow it, either. Changing it any other way it would cause major changes of a component which would belong to another PR.

2022-08-01 14:58 UTC, abasic approved these changes

2022-08-01 18:02 UTC, Lnola commented on frontend/src/components/profile/ProfileSidebar.vue
> +        <user-form :inputs="formInputs" class="user-profile-form" disabled />
can it please be added as a task!

2022-08-01 18:06 UTC, Lnola commented on frontend/src/components/profile/ProfileSidebar.vue
> +  height: 100vh;
if by any chance the scrollbar right is shown/needs to be displayed `vw` it will mess up scroll left-right. `vh` is ok here, but since we have the overlay being `inset: 0` why not `%` for all

2022-08-01 18:10 UTC, Lnola approved these changes
Looks good now!

2022-08-02 06:39 UTC, Lnola commented on frontend/src/components/profile/ProfileSidebar.vue
> +        <user-form :inputs="formInputs" class="user-profile-form" disabled />
I have a solution to this, I'm adding it as a comment where it should be implemented

2022-08-02 06:40 UTC, Lnola commented on frontend/src/components/profile/ProfileSidebar.vue
> +      formInputs.fullName.value = fullName;
you could do this to remove the `fullName` if it is empty
```
if (formInputs.fullName.value.length === 0) delete formInputs.fullName;
else formInputs.fullName.value = fullName;
```

2022-08-02 06:44 UTC, Lnola commented on frontend/src/components/home/HomePage.vue
> +import ProfileSidebar from '@/components/profile/ProfileSidebar.vue';
I'm getting import sorting errors here. No big deal, probably just from merging, but please fix 😄

2022-08-02 07:08 UTC, abasic approved these changes

2022-08-02 07:11 UTC, merged