Tag-based Room Recommendation
ExtensionEngine/chichet pull request #57
Opened 2022-08-03 12:54 UTC by sandje00

THIS PR:

- Add more seed data
- Add recommended rooms migration with materialized view, unique index on `userId` and `rooomId` materialized view fields, trigger and function to refresh materialized view
- Add recommended room model and map it to materialized view
- Add room recommendation fetching controller function

Related issues:
Closes #53

[Recommendation Query Explanation](https://github.com/ExtensionEngine/chichet/wiki/Tag-Based-Room-Recommendation)

2022-08-09 10:24 UTC, Lnola requested changes
Minor changes required, good job!

2022-08-09 10:24 UTC, Lnola commented on backend/src/room/room.controller.ts
> +const RECOMMENDED_ROOMS_LIMIT = 4;
nitpicki - could this be moved to `shared/constants`?

2022-08-09 10:26 UTC, Lnola commented on backend/src/shared/database/migrations/20220807150228-add-recommended-rooms.js
> +    CREATE MATERIALIZED VIEW ${MATERIALIZED_VIEW_NAME}
Just one general comment, please write an explanation to each of these queries, understanding what each does was a struggle both for me and for you when you were explaining them for me 😄

2022-08-09 10:27 UTC, sandje00 commented on backend/src/room/recommendedRoom.model.ts
> +    const { INTEGER } = dataTypes;
I left it like this because in the following line it is necessary passing the entire `dataTypes` object to `Room.fields()` in order to obtain room fields needed for this model.

2022-08-09 10:40 UTC, abasic reviewed
One minor comment 👍

2022-08-09 10:40 UTC, abasic commented on backend/src/shared/database/seeders/20220803093705-users.js
> +const bcrypt = require('bcrypt');
Could `import` have been used here since the project is using node v18? Maybe the extension of the file would need to be `.mjs`.

2022-08-09 13:45 UTC, sandje00 commented on backend/src/shared/database/seeders/20220803093705-users.js
> +const bcrypt = require('bcrypt');
The approach with `.mjs` file did not give desired result; the seeder did not run at all. There is a way of using ES modules with Sequelize migrations / seeds, but it would be necessary to introduce two new dependencies to the project, but within the team we have agreed not to and leave it this way.

2022-08-10 08:36 UTC, Lnola approved these changes

2022-08-10 12:31 UTC, abasic approved these changes

2022-08-11 07:16 UTC, merged