Feature/backend setup
ExtensionEngine/chichet pull request #7
Opened 2022-07-08 13:44 UTC by Lnola

2022-07-12 08:57 UTC, Lnola commented on backend/src/app.ts
> +
Added!

2022-07-12 08:59 UTC, Lnola commented on pnpm.sh
> +docker-compose up
since it was a .sh file i didn't know if it would work. Tested it now, seems ok 👍

2022-07-12 09:43 UTC, sandje00 approved these changes

2022-07-12 11:57 UTC, abasic requested changes
Most of the comments are lint nitpicks 😄

2022-07-12 13:13 UTC, Lnola commented on backend/src/message/message.model.ts
> +        type: STRING,
we overlooked that, its TEXT now

2022-07-12 13:14 UTC, Lnola commented on backend/src/message/message.model.ts
> +      timestamps: false,
We didn't think we would need them since we are not doing edit/create for most models (instead using the seeded ones)

2022-07-12 13:16 UTC, Lnola commented on backend/src/message/message.model.ts
> +      timestamps: false,
The ones that need timestamps, room/user interactions mainly, have the ones they need declared

2022-07-12 13:31 UTC, Lnola commented on backend/src/user/user.model.ts
> +    this.belongsToMany(Room, {
The thought proces was - visually grouping the keys belonging to the same connection. 

For example
- User - UserTag - Tag
- User - Message - Room
- User - UserRoomInteraction - Room

The empty line was intentional to visually group same relation associations

2022-07-12 14:17 UTC, Lnola commented on backend/src/tag/tag.model.ts
> +      label: {
Added as task, TBA

2022-07-12 14:22 UTC, Lnola commented on backend/src/shared/database/seeders/20220711204114-room-tags.js
> +  async up(queryInterface) {
sequelize-cli adds it by default, forgot to remove it

2022-07-12 16:05 UTC, abasic requested changes
These two things need to be resolved and this can be merged.

2022-07-13 06:46 UTC, abasic approved these changes

2022-07-13 06:46 UTC, merged