Common Components
ExtensionEngine/chichet pull request #8
Opened 2022-07-11 08:09 UTC by sandje00

THIS PR:

- Base frontend folder structure
- Base button
- Base input
- Base field
- Base base textarea

Related issues:
Closes #5

2022-07-12 08:07 UTC, Lnola requested changes
Needs a few simple changes, nothing major

2022-07-12 08:07 UTC, Lnola commented on frontend/src/components/common/vTextarea.vue
> +  resize: none;
remove border

2022-07-12 08:38 UTC, sandje00 commented on frontend/src/components/common/vButton.vue
> +  <button class="button">
It is not necessary, since `click` event handling will be defined in a context of a component in which base button is used.

2022-07-12 09:16 UTC, Lnola commented on frontend/src/components/common/vButton.vue
> +  <button class="button">
react mentality :)

2022-07-12 09:45 UTC, Lnola approved these changes
Looks good!

2022-07-12 10:45 UTC, abasic requested changes
Some of the comments can be applied to more than the line they were written on. Please apply them everywhere they are applicable.

2022-07-12 10:45 UTC, abasic commented on frontend/src/App.vue
> +#app {
Please move this to the `global.css` file.

2022-07-12 10:45 UTC, abasic commented on frontend/src/components/common/ChiButton.vue
> +  <button class="button">
Please use more specific class names.

2022-07-12 10:45 UTC, abasic commented on frontend/src/components/common/ChiButton.vue
> +<style>
Please use the `scoped` attribute if appropriate.

2022-07-12 10:45 UTC, abasic commented on frontend/src/composables/useModelValue.js
> +export default function useModelValue(emit) {
Please use the `v-bind="$attrs"` approach if applicable.

2022-07-12 12:43 UTC, abasic commented on frontend/src/components/common/ChiInput.vue
> +  <input v-bind="{ ...$attrs, onInput: updateModelValue }" :value="modelValue" class="chi-input" />
The code I had in mind when I mentioned `$attrs` being used is this:
```vue
<input v-bind="$attrs" class="chi-input">
```
I believe this would achieve the same desired behavior. The reason is that a parent component could use it in the same way as a regular input tag. So `chi-input` and `input` could be interchangeable.
```vue
<input v-model="xyz">
<chi-input v-model="abc">
```
and
```vue
<input @input="update($event)" :value="xyz">
<chi-input @input="update($event)" :value="abc">
```

I am not certain if the way it is written now could be used interchangeably. Looking at it again, I am not sure a `v-model` would work correctly. Interchangeability in this case, to me, is a worthwhile goal because it makes the interface of the custom component the same as the native one and it is more straightforward to use.

Please take a look and see if what I wrote makes sense and is in line with your goals.

2022-07-13 08:57 UTC, abasic commented on frontend/src/components/common/ChiInput.vue
> +  <input v-bind="{ ...$attrs, onInput: updateModelValue }" :value="modelValue" class="chi-input" />
`v-model` was changed in Vue 3 so this does not work.

2022-07-13 12:05 UTC, merged