Tag Intensity Based Recommendation
ExtensionEngine/chichet pull request #87
Opened 2022-08-18 11:59 UTC by sandje00

Closes #84

2022-08-18 13:50 UTC, Lnola commented on backend/src/room/recommendedRoom.model.ts
> +      tagsNumDiff: { type: INTEGER },
nitpick: I am not a fan of shortened names (unless there is a reason) since I think it makes the code less readable

2022-08-18 13:50 UTC, Lnola commented on backend/src/userTag/userTag.model.ts
> +        allowNull: true,
since intensity will be calculated as a percentage perhaps `decimal` would fit better. That way we don't have to use `round` and we don't have to multiply it by 10

2022-08-18 13:50 UTC, Lnola commented on backend/src/userTag/userTag.model.ts
> +        allowNull: true,
we could add a constraint min/max `0 < intensity < 1`  as well

2022-08-18 13:50 UTC, Lnola commented on backend/src/shared/database/seeders/20220803123242-user-tags.js
> +      { userId: 6, tagId: 31, intensity: 4 },
these need to be updated if intensity `INTEGER`/`DECIMAL` is changed

2022-08-18 13:50 UTC, Lnola commented on backend/src/shared/database/migrations/20220817094029-add-intensity-to-user-tag.js
> +      type: Sequelize.INTEGER,
this need to be updated if intensity `INTEGER`/`DECIMAL` is changed

2022-08-18 14:29 UTC, abasic submitted a review, later dismissed

2022-08-19 09:47 UTC, abasic requested changes

2022-08-19 09:47 UTC, abasic commented on backend/src/shared/database/migrations/20220817203222-add-intensity-to-recommended-rooms.js
> +  },
Thinking about it, maybe transactions should be used here as well.

2022-08-19 11:04 UTC, sandje00 commented on backend/src/shared/database/migrations/20220817094029-add-intensity-to-user-tag.js
> +};
Since adding transactions to migrations with multiple queries would introduce changes to files that are not part of this PR as well, I will add it as a part of a different PR.

2022-08-22 08:27 UTC, abasic approved these changes
I'll approve this but I generally recommend the usage of [managed transactions](https://sequelize.org/docs/v6/other-topics/transactions/#managed-transactions) because `commit` and `rollback` do not need to be called directly but are done automatically.

2022-08-22 08:52 UTC, Lnola approved these changes

2022-08-22 09:06 UTC, merged